/*
 *
 * MyPage constants
 *
 */

export const DEFAULT_ACTION = 'app/MyPage/DEFAULT_ACTION';
export const MYPAGE_FINDBYID = 'app/MyPage/MYPAGE_FINDBYID';
export const MYPAGE_FINDBYID_SUCCESS = 'app/MyPage/MYPAGE_FINDBYID_SUCCESS';
export const MYPAGE_FINDBYID_ERROR = 'app/MyPage/MYPAGE_FINDBYID_ERROR';
export const MYPAGE_MYBOARDLIST = 'app/MyPage/MYPAGE_MYBOARDLIST';
export const MYPAGE_MYBOARDLIST_SUCCESS =
  'app/MyPage/MYPAGE_MYBOARDLIST_SUCCESS';
export const MYPAGE_MYBOARDLIST_ERROR = 'app/MyPage/MYPAGE_MYBOARDLIST_ERROR';
export const MYPAGE_MYREPLYLIST = 'app/MyPage/MYPAGE_MYREPLYLIST';
export const MYPAGE_MYREPLYLIST_SUCCESS =
  'app/MyPage/MYPAGE_MYREPLYLIST_SUCCESS';
export const MYPAGE_MYREPLYLIST_ERROR = 'app/MyPage/MYPAGE_MYREPLYLIST_ERROR';
export const MYPAGE_NOTELIST = 'app/MyPage/MYPAGE_NOTELIST';
export const MYPAGE_NOTELIST_SUCCESS = 'app/MyPage/MYPAGE_NOTELIST_SUCCESS';
export const MYPAGE_NOTELIST_ERROR = 'app/MyPage/MYPAGE_NOTELIST_ERROR';
export const MYPAGE_FOLLOWLIST = 'app/MyPage/MYPAGE_FOLLOWLIST';
export const MYPAGE_FOLLOWLIST_SUCCESS = 'app/MyPage/MYPAGE_FOLLOWLIST_SUCCESS';
export const MYPAGE_FOLLOWLIST_ERROR = 'app/MyPage/MYPAGE_FOLLOWLIST_ERROR';
export const FIND_PROFILE_IMAGE = 'app/MyPage/FIND_PROFILE_IMAGE';
export const FIND_PROFILE_IMAGE_SUCCESS =
  'app/MyPage/FIND_PROFILE_IMAGE_SUCCESS';
export const FIND_PROFILE_IMAGE_ERROR = 'app/MyPage/FIND_PROFILE_IMAGE_ERROR';
